# Generated by Django 2.1.7 on 2019-04-10 03:09

import concurrency.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseConcurrentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('_ctime', models.DateTimeField(auto_now_add=True)),
                ('_mtime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('_version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('_ctime', models.DateTimeField(auto_now_add=True)),
                ('_mtime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ArgumentDefine',
            fields=[
                ('baseconcurrentmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wfapp.BaseConcurrentModel')),
                ('name', models.CharField(max_length=255)),
                ('argument_type', models.CharField(choices=[('int', 'int'), ('string', 'string'), ('choice', 'choice'), ('text', 'text')], max_length=255)),
                ('extra_args', django_extensions.db.fields.json.JSONField(default={})),
            ],
            bases=('wfapp.baseconcurrentmodel',),
        ),
        migrations.CreateModel(
            name='Hook',
            fields=[
                ('baseconcurrentmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='wfapp.BaseConcurrentModel')),
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('wfapp.baseconcurrentmodel', models.Model),
        ),
        migrations.CreateModel(
            name='HookAuth',
            fields=[
                ('baseconcurrentmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='wfapp.BaseConcurrentModel')),
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            bases=('wfapp.baseconcurrentmodel',),
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('baseconcurrentmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wfapp.BaseConcurrentModel')),
                ('arguments', django_extensions.db.fields.json.JSONField(default={})),
                ('step_status', models.CharField(choices=[('waiting', 'waiting'), ('running', 'running'), ('success', 'success'), ('fail', 'fail')], default='waiting', max_length=255)),
                ('step_return', django_extensions.db.fields.json.JSONField(default={})),
                ('from_step', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='wfapp.Step')),
            ],
            bases=('wfapp.baseconcurrentmodel',),
        ),
        migrations.CreateModel(
            name='StepDefine',
            fields=[
                ('baseconcurrentmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wfapp.BaseConcurrentModel')),
                ('name', models.CharField(max_length=255)),
            ],
            bases=('wfapp.baseconcurrentmodel',),
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('baseconcurrentmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wfapp.BaseConcurrentModel')),
                ('name', models.CharField(max_length=255)),
                ('start_step_define', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wfapp.StepDefine')),
            ],
            bases=('wfapp.baseconcurrentmodel',),
        ),
        migrations.CreateModel(
            name='HttpHook',
            fields=[
                ('hook_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wfapp.Hook')),
                ('api', models.CharField(max_length=255)),
                ('method', models.CharField(choices=[('get', 'get'), ('put', 'put'), ('post', 'post'), ('delete', 'delete')], max_length=255)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('wfapp.hook',),
        ),
        migrations.CreateModel(
            name='TokenAuth',
            fields=[
                ('hookauth_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wfapp.HookAuth')),
                ('token', models.CharField(max_length=255)),
                ('header', models.CharField(default='Authorization', max_length=255)),
                ('prefix', models.CharField(default='Token', max_length=255)),
            ],
            bases=('wfapp.hookauth',),
        ),
        migrations.AddField(
            model_name='workflow',
            name='workflow_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wfapp.WorkflowTemplate'),
        ),
        migrations.AddField(
            model_name='stepdefine',
            name='after_commit',
            field=models.ManyToManyField(blank=True, default=[], related_name='after_commit_hook', to='wfapp.Hook'),
        ),
        migrations.AddField(
            model_name='stepdefine',
            name='after_fail_submit',
            field=models.ManyToManyField(blank=True, default=[], related_name='after_fail_submit_hook', to='wfapp.Hook'),
        ),
        migrations.AddField(
            model_name='stepdefine',
            name='after_init',
            field=models.ManyToManyField(blank=True, default=[], related_name='after_init_hook', to='wfapp.Hook'),
        ),
        migrations.AddField(
            model_name='stepdefine',
            name='after_reject',
            field=models.ManyToManyField(blank=True, default=[], related_name='after_reject_hook', to='wfapp.Hook'),
        ),
        migrations.AddField(
            model_name='stepdefine',
            name='after_submit',
            field=models.ManyToManyField(blank=True, default=[], related_name='after_submit_hook', to='wfapp.Hook'),
        ),
        migrations.AddField(
            model_name='stepdefine',
            name='after_success_submit',
            field=models.ManyToManyField(blank=True, default=[], related_name='after_success_submit_hook', to='wfapp.Hook'),
        ),
        migrations.AddField(
            model_name='stepdefine',
            name='before_commit',
            field=models.ManyToManyField(blank=True, default=[], related_name='before_commit_hook', to='wfapp.Hook'),
        ),
        migrations.AddField(
            model_name='stepdefine',
            name='before_fail_submit',
            field=models.ManyToManyField(blank=True, default=[], related_name='before_fail_submit_hook', to='wfapp.Hook'),
        ),
        migrations.AddField(
            model_name='stepdefine',
            name='before_init',
            field=models.ManyToManyField(blank=True, default=[], related_name='before_init_hook', to='wfapp.Hook'),
        ),
        migrations.AddField(
            model_name='stepdefine',
            name='before_reject',
            field=models.ManyToManyField(blank=True, default=[], related_name='before_reject_hook', to='wfapp.Hook'),
        ),
        migrations.AddField(
            model_name='stepdefine',
            name='before_submit',
            field=models.ManyToManyField(blank=True, default=[], related_name='before_submit_hook', to='wfapp.Hook'),
        ),
        migrations.AddField(
            model_name='stepdefine',
            name='before_success_submit',
            field=models.ManyToManyField(blank=True, default=[], related_name='before_success_submit_hook', to='wfapp.Hook'),
        ),
        migrations.AddField(
            model_name='stepdefine',
            name='commit_stepdefines',
            field=models.ManyToManyField(blank=True, default=[], related_name='commit_stepdefine', to='wfapp.StepDefine'),
        ),
        migrations.AddField(
            model_name='stepdefine',
            name='fail_stepdefines',
            field=models.ManyToManyField(blank=True, default=[], related_name='fail_stepdefine', to='wfapp.StepDefine'),
        ),
        migrations.AddField(
            model_name='stepdefine',
            name='reject_stepdefines',
            field=models.ManyToManyField(blank=True, default=[], related_name='reject_stepdefine', to='wfapp.StepDefine'),
        ),
        migrations.AddField(
            model_name='stepdefine',
            name='success_stepdefines',
            field=models.ManyToManyField(blank=True, default=[], related_name='success_stepdefine', to='wfapp.StepDefine'),
        ),
        migrations.AddField(
            model_name='stepdefine',
            name='workflow_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_defines', to='wfapp.WorkflowTemplate'),
        ),
        migrations.AddField(
            model_name='step',
            name='step_define',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wfapp.StepDefine'),
        ),
        migrations.AddField(
            model_name='step',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wfapp.Workflow'),
        ),
        migrations.AddField(
            model_name='hook',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_wfapp.hook_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='argumentdefine',
            name='step_define',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arguments', to='wfapp.StepDefine'),
        ),
        migrations.AddField(
            model_name='httphook',
            name='auth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wfapp.HookAuth'),
        ),
    ]
